SELECT O_CUSTKEY, sum(O_TOTALPRICE), count(O_ORDERKEY) AS cnt_order FROM ORDERS GROUP BY O_CUSTKEY HAVING cnt_order > 20;

UPDATE LINEITEM SET L_TAX = L_TAX * 1.10 WHERE L_DISCOUNT > 0.02;

SELECT L_ORDERKEY, avg(L_DISCOUNT) AS avg_dis FROM LINEITEM WHERE L_TAX < 0.05 GROUP BY L_ORDERKEY ORDER BY avg_dis DESC LIMIT 10;

SELECT L_ORDERKEY, L_LINENUMBER FROM LINEITEM EXCEPT SELECT DISTINCT L1.L_ORDERKEY, L1.L_LINENUMBER FROM LINEITEM AS L1, LINEITEM AS L2 WHERE L1.L_DISCOUNT < L2.L_DISCOUNT;
    SELECT L_ORDERKEY, L_LINENUMBER FROM LINEITEM AS L1 WHERE NOT EXISTS (SELECT * FROM LINEITEM AS L2 WHERE L1.L_DISCOUNT < L2.L_DISCOUNT);
    SELECT L_ORDERKEY, L_LINENUMBER FROM LINEITEM WHERE L_DISCOUNT = (SELECT L_DISCOUNT FROM LINEITEM ORDER BY L_DISCOUNT DESC LIMIT 1);

SELECT PS_PARTKEY, sum(PS_AVAILQTY) FROM PARTSUPP GROUP BY PS_PARTKEY;

SELECT * FROM CUSTOMER WHERE c_custkey IN (SELECT o_custkey FROM ORDERS WHERE o_totalprice < 10000);
